silo:
  user:
    host: 'localhost'
    port: 8081
    endpoints:
      user: 'user'
      admin: 'admin'
  video:
    host: 'localhost'
    port: 8083
    endpoints:
      search: 'search'
      playlists: 'playlists'
  history:
    host: 'localhost'
    port: 8084
    endpoints:
      history: 'history'

